fix: make Custom ClassLoader compatible with tomcat 9.0.62+
squashes commits

Date: 2019-03-27 17:34:46 +0800
- test-fix: workarounds exception with <JarScanner scanClassPath="false" /> since tomcat 9.0.16
  > java.lang.IllegalArgumentException: More than one fragment with the name [spring_web] was found ...

Date: 2022-08-12 13:45:12 +0800
- fix: compatible fixes for tomcat 9.0.62+
  tomcat 9.0.62+ org.apache.catalina.loader.WebappClassLoaderBase#getResources is Deprecated and can not be used

Date: now
- dependency: bump tomcat version to 9.0.73